"""
52-week personal finance curriculum.
Each week has a theme with 7 daily sub-topics.
Claude generates a fresh article for each topic daily.
"""

CURRICULUM = [
    {
        "week": 1,
        "theme": "Money Fundamentals",
        "topics": [
            "Why money exists and how it actually works",
            "The time value of money — why $1 today beats $1 tomorrow",
            "Compound interest: the most powerful force in finance",
            "Inflation: the silent tax on your savings",
            "The difference between assets and liabilities",
            "Net worth: the only number that matters",
            "The psychology of money — why we make irrational financial decisions",
        ],
    },
    {
        "week": 2,
        "theme": "Banking & Cash Management",
        "topics": [
            "High-yield savings: why your big bank is stealing from you",
            "Checking vs savings vs money market accounts",
            "FDIC insurance — what's actually protected and what's not",
            "How to structure your bank accounts for automation",
            "Emergency fund: how much you need and where to keep it",
            "CDs, T-bills, and cash equivalents explained",
            "The hidden fees banks charge and how to avoid every one",
        ],
    },
    {
        "week": 3,
        "theme": "Credit Scores & Reports",
        "topics": [
            "How your credit score is actually calculated (the real formula)",
            "The 5 factors that control your credit score",
            "How to read your credit report and spot errors",
            "Credit utilization: the 30% rule and why it matters",
            "Hard pulls vs soft pulls — when to worry",
            "How to dispute errors on your credit report",
            "Building credit from zero: strategies that actually work",
        ],
    },
    {
        "week": 4,
        "theme": "Credit Cards",
        "topics": [
            "How credit card companies make money off you",
            "APR, penalty APR, and how interest compounds daily",
            "Balance transfers: the 0% APR arbitrage strategy",
            "Cash back vs points vs miles — which rewards matter",
            "The minimum payment trap: why banks want you to pay $25/month",
            "When to close a credit card (and when never to)",
            "How to negotiate a lower APR with one phone call",
        ],
    },
    {
        "week": 5,
        "theme": "Debt Elimination",
        "topics": [
            "Good debt vs bad debt: a framework for borrowing",
            "Snowball vs avalanche: the math and the psychology",
            "How to calculate the true cost of debt",
            "Debt consolidation: when it helps and when it's a trap",
            "Student loans: income-driven repayment and forgiveness programs",
            "Medical debt: your rights and negotiation strategies",
            "The debt-free date: calculating your payoff timeline",
        ],
    },
    {
        "week": 6,
        "theme": "Budgeting That Works",
        "topics": [
            "Why most budgets fail (and what to do instead)",
            "The 50/30/20 rule and its variations",
            "Zero-based budgeting for control freaks",
            "Automating your finances: pay yourself first",
            "Tracking spending without losing your mind",
            "Lifestyle inflation: the silent wealth killer",
            "How to budget on irregular income",
        ],
    },
    {
        "week": 7,
        "theme": "Investing Basics",
        "topics": [
            "Why you need to invest (savings accounts won't cut it)",
            "Stocks, bonds, and index funds explained simply",
            "Risk tolerance: how much volatility can you actually handle",
            "Dollar-cost averaging: the boring strategy that wins",
            "The S&P 500: why most professionals can't beat it",
            "Expense ratios: the fee that eats your returns",
            "How to open a brokerage account and buy your first index fund",
        ],
    },
    {
        "week": 8,
        "theme": "Retirement Accounts",
        "topics": [
            "401(k) explained: free money from your employer",
            "Traditional vs Roth: the tax decision that matters most",
            "IRA contribution limits and the backdoor Roth strategy",
            "HSA: the triple-tax-advantaged secret weapon",
            "Required minimum distributions and why they matter",
            "Target-date funds: set-it-and-forget-it retirement",
            "How much you actually need to retire (the 4% rule)",
        ],
    },
    {
        "week": 9,
        "theme": "Tax Strategy",
        "topics": [
            "How federal income tax brackets actually work (it's not what you think)",
            "Standard deduction vs itemizing: how to decide",
            "Tax-advantaged accounts: the order of operations",
            "Capital gains tax: short-term vs long-term rates",
            "Tax-loss harvesting: turning losses into savings",
            "State income tax: how your location affects your wealth",
            "Estimated taxes and why freelancers get surprised",
        ],
    },
    {
        "week": 10,
        "theme": "Real Estate Investing",
        "topics": [
            "Renting vs buying: the real math (not what realtors tell you)",
            "How to analyze a rental property in 10 minutes",
            "Cap rate, cash-on-cash return, and other key metrics",
            "The 1% rule and 50% rule for screening deals",
            "Depreciation: the tax benefit that makes real estate powerful",
            "House hacking: living for free while building wealth",
            "REITs: real estate investing without being a landlord",
        ],
    },
    {
        "week": 11,
        "theme": "Insurance Essentials",
        "topics": [
            "Health insurance: understanding premiums, deductibles, and copays",
            "Life insurance: term vs whole life (one is almost always better)",
            "Disability insurance: protecting your biggest asset — your income",
            "Auto insurance: how to save without cutting coverage",
            "Renters insurance: the cheapest coverage you're probably skipping",
            "Umbrella insurance: when your net worth needs extra protection",
            "How to audit your insurance and eliminate waste",
        ],
    },
    {
        "week": 12,
        "theme": "Negotiation & Income",
        "topics": [
            "How to negotiate your salary (with exact scripts)",
            "The total compensation equation: base, bonus, equity, benefits",
            "When to ask for a raise and how to justify it with data",
            "Side income: realistic ways to earn an extra $500-$2000/month",
            "The freelancer's guide to pricing your time",
            "How to evaluate a job offer beyond the salary number",
            "Building multiple income streams for financial resilience",
        ],
    },
    {
        "week": 13,
        "theme": "Behavioral Finance",
        "topics": [
            "Loss aversion: why losing $100 hurts more than gaining $100 feels good",
            "Anchoring bias and how it makes you overpay",
            "FOMO investing: why chasing trends destroys returns",
            "Sunk cost fallacy: when to walk away from bad investments",
            "Mental accounting: the reason you treat money differently",
            "Present bias: why we choose $50 now over $100 later",
            "How to build systems that protect you from yourself",
        ],
    },
    {
        "week": 14,
        "theme": "Estate Planning Basics",
        "topics": [
            "Why everyone over 18 needs a will (yes, really)",
            "Power of attorney: financial and medical directives",
            "Beneficiary designations: the document that overrides your will",
            "Living trusts: when they make sense and when they don't",
            "Digital estate planning: passwords, crypto, and online accounts",
            "How to talk to aging parents about their finances",
            "The cost of dying without a plan (intestacy laws explained)",
        ],
    },
    {
        "week": 15,
        "theme": "Advanced Investing",
        "topics": [
            "Asset allocation: the decision that determines 90% of your returns",
            "International diversification: should you invest outside the US?",
            "Bond funds vs individual bonds: pros and cons",
            "Factor investing: value, momentum, and size premiums",
            "Alternative investments: private equity, hedge funds, commodities",
            "Rebalancing: when and how to adjust your portfolio",
            "Tax-efficient fund placement: which account holds what",
        ],
    },
    {
        "week": 16,
        "theme": "Major Purchases",
        "topics": [
            "Buying a car: new vs used and the depreciation math",
            "How much house can you actually afford (not what the bank says)",
            "The true cost of homeownership beyond the mortgage",
            "When financing makes sense and when to pay cash",
            "Extended warranties and protection plans: almost always a waste",
            "How to negotiate any major purchase (cars, appliances, services)",
            "The 24-hour rule: defeating impulse spending on big items",
        ],
    },
    {
        "week": 17,
        "theme": "Subscription Economy",
        "topics": [
            "The subscription trap: how $10/month becomes $3,600/year",
            "How to audit your subscriptions in 15 minutes",
            "Price anchoring in subscription tiers (how companies upsell you)",
            "The true cost of streaming: when bundles make sense",
            "Software subscriptions vs one-time purchases",
            "Subscription fatigue: a framework for what to keep",
            "Negotiating lower rates on subscriptions you want to keep",
        ],
    },
    {
        "week": 18,
        "theme": "Financial Independence",
        "topics": [
            "The FIRE movement: financial independence, retire early",
            "Your FIRE number: 25x your annual expenses",
            "Coast FIRE: the most achievable version of early retirement",
            "Barista FIRE and part-time work in early retirement",
            "Safe withdrawal rates: why 4% might not be enough",
            "Geographic arbitrage: living where your money goes further",
            "The one-more-year syndrome: when to actually pull the trigger",
        ],
    },
    {
        "week": 19,
        "theme": "Crypto & Digital Assets",
        "topics": [
            "Bitcoin: what it is, how it works, and why it matters",
            "Ethereum and smart contracts: the programmable money layer",
            "Crypto portfolio sizing: how much is too much",
            "DeFi basics: lending, borrowing, and yield farming risks",
            "Crypto taxes: how the IRS tracks your trades",
            "Security: hardware wallets, seed phrases, and not getting hacked",
            "The bear case for crypto: risks you need to understand",
        ],
    },
    {
        "week": 20,
        "theme": "Relationships & Money",
        "topics": [
            "Money conversations before marriage (what to discuss)",
            "Joint accounts vs separate accounts: the 3-account system",
            "How to split expenses fairly when incomes differ",
            "Prenuptial agreements: protection, not pessimism",
            "Teaching kids about money at every age",
            "Financial infidelity: hidden spending and secret debt",
            "Divorce and finances: protecting yourself and starting over",
        ],
    },
    {
        "week": 21,
        "theme": "Tax Optimization Advanced",
        "topics": [
            "Mega backdoor Roth: the $69K retirement hack",
            "Qualified business income deduction (Section 199A)",
            "Charitable giving strategies: donor-advised funds and bunching",
            "529 plans: tax-free education savings and state deductions",
            "How to use a CPA vs doing your own taxes",
            "Estimated tax payments: avoiding the underpayment penalty",
            "Year-end tax planning moves to make before December 31",
        ],
    },
    {
        "week": 22,
        "theme": "Career & Wealth Building",
        "topics": [
            "The career capital framework: skills that pay exponentially",
            "Why your network is worth more than your portfolio (early on)",
            "Equity compensation: RSUs, stock options, and ISOs explained",
            "When to start a business vs climb the corporate ladder",
            "The millionaire math: how income, savings rate, and time interact",
            "Professional development: the investments that 10x your income",
            "Career risk management: diversifying your human capital",
        ],
    },
    {
        "week": 23,
        "theme": "Market Cycles & Crashes",
        "topics": [
            "A brief history of market crashes (and what happened next)",
            "Bear markets: how to survive and even thrive",
            "Dollar-cost averaging during a downturn: the data",
            "Why market timing fails: the cost of missing the best 10 days",
            "Recessions and your portfolio: what to do (and not do)",
            "Black swan events and tail risk protection",
            "The psychology of panic selling and how to avoid it",
        ],
    },
    {
        "week": 24,
        "theme": "Entrepreneurship & Side Hustles",
        "topics": [
            "Starting a business: LLC vs S-Corp vs sole proprietor",
            "Business banking: separating personal and business finances",
            "Pricing strategies: value-based pricing vs cost-plus",
            "Self-employment taxes: the 15.3% surprise",
            "Business deductions: what you can (and can't) write off",
            "Scaling from side hustle to full-time: when to make the leap",
            "Building a business that runs without you",
        ],
    },
    {
        "week": 25,
        "theme": "Healthcare & Finances",
        "topics": [
            "The HSA triple tax advantage: the best retirement account nobody uses",
            "Health insurance marketplace: subsidies and cost savings",
            "Medical debt: negotiating bills down by 50-80%",
            "COBRA vs marketplace: what to do when you lose employer coverage",
            "Long-term care: planning for costs most people ignore",
            "Mental health and money: breaking the stress-spending cycle",
            "Open enrollment mistakes that cost thousands",
        ],
    },
    {
        "week": 26,
        "theme": "Mid-Year Financial Review",
        "topics": [
            "How to do a mid-year financial checkup in 30 minutes",
            "Rebalancing your portfolio: when and how",
            "Are you on track for your annual goals? Adjusting course",
            "Tax planning mid-year: moves to make now, not December",
            "Insurance audit: are you over-insured or under-insured?",
            "Reviewing your automated transfers and savings rate",
            "Setting financial goals for the second half of the year",
        ],
    },
    {
        "week": 27,
        "theme": "Global Economics",
        "topics": [
            "How the Federal Reserve affects your wallet",
            "Interest rates: why the Fed rate matters for mortgages and savings",
            "Inflation vs deflation: what each means for your money",
            "The US dollar as world reserve currency (and why it matters)",
            "Trade deficits and tariffs: impact on your investments",
            "Emerging markets: opportunity and risk",
            "How global events move your 401(k)",
        ],
    },
    {
        "week": 28,
        "theme": "Advanced Real Estate",
        "topics": [
            "1031 exchanges: deferring capital gains on property sales",
            "Cost segregation studies: accelerating depreciation deductions",
            "Short-term rentals (Airbnb) vs long-term: financial comparison",
            "Real estate syndications: passive investing in large deals",
            "Commercial real estate basics for residential investors",
            "The BRRRR method: Buy, Rehab, Rent, Refinance, Repeat",
            "Real estate market cycles: when to buy and when to wait",
        ],
    },
    {
        "week": 29,
        "theme": "Financial Tools & Technology",
        "topics": [
            "Automated investing: robo-advisors vs DIY portfolios",
            "High-yield savings accounts: current best rates and how to compare",
            "Budgeting apps: what actually works vs what wastes your time",
            "Credit monitoring: free tools vs paid services",
            "Tax software comparison: TurboTax vs FreeTaxUSA vs CPA",
            "Financial aggregation: seeing all your money in one place",
            "Security: two-factor auth, password managers, and protecting your finances",
        ],
    },
    {
        "week": 30,
        "theme": "Social Security & Medicare",
        "topics": [
            "How Social Security benefits are calculated",
            "When to claim Social Security: 62 vs 67 vs 70",
            "Spousal and survivor benefits: maximizing as a couple",
            "Medicare basics: Parts A, B, C, D and what each covers",
            "Medigap vs Medicare Advantage: how to choose",
            "Social Security taxation: the stealth tax on retirees",
            "Will Social Security be there for you? What the math says",
        ],
    },
    {
        "week": 31,
        "theme": "Wealth Protection",
        "topics": [
            "Asset protection strategies for high-net-worth individuals",
            "Umbrella insurance: when you need more than standard coverage",
            "Trusts for asset protection: irrevocable vs revocable",
            "Identity theft: prevention, detection, and recovery",
            "Fraud awareness: common financial scams targeting all ages",
            "Cybersecurity for your financial accounts",
            "Natural disaster preparedness: insurance and financial planning",
        ],
    },
    {
        "week": 32,
        "theme": "International Finance",
        "topics": [
            "FBAR and FATCA: reporting requirements for foreign accounts",
            "Foreign earned income exclusion for expats",
            "Currency risk: how exchange rates affect your investments",
            "International real estate: buying property abroad",
            "Tax treaties: avoiding double taxation",
            "Sending money internationally: cheapest methods",
            "Retirement abroad: countries where your dollar goes furthest",
        ],
    },
    {
        "week": 33,
        "theme": "Generational Wealth",
        "topics": [
            "The gift tax: annual exclusions and lifetime limits",
            "529 plans for grandchildren: superfunding strategy",
            "Family limited partnerships for wealth transfer",
            "Generation-skipping transfer tax: what it is and who it affects",
            "Teaching the next generation about money management",
            "Family governance: keeping wealth through generations",
            "The statistics on generational wealth loss (and how to beat them)",
        ],
    },
    {
        "week": 34,
        "theme": "Financial Resilience",
        "topics": [
            "Job loss preparation: the financial firewall strategy",
            "Recession-proofing your finances: a practical checklist",
            "How to rebuild after financial disaster",
            "Emergency fund tiers: from basic to bulletproof",
            "Income diversification: not all eggs in one basket",
            "The importance of a financial support network",
            "Stress testing your finances: what happens if income drops 50%?",
        ],
    },
    {
        "week": 35,
        "theme": "Charitable Giving & Impact",
        "topics": [
            "Donor-advised funds: the tax-efficient way to give",
            "Qualified charitable distributions from IRAs",
            "Volunteering and pro bono: non-monetary impact",
            "Impact investing: aligning your portfolio with your values",
            "Community development financial institutions (CDFIs)",
            "Starting a private foundation vs donor-advised fund",
            "Tax benefits of charitable giving: what actually saves you money",
        ],
    },
    {
        "week": 36,
        "theme": "Housing Deep Dive",
        "topics": [
            "Mortgage types: fixed vs ARM vs interest-only",
            "How to shop for a mortgage and compare APRs",
            "Private mortgage insurance (PMI): how to avoid or remove it",
            "Refinancing: when the math works and when it doesn't",
            "Home equity: HELOC vs home equity loan vs cash-out refi",
            "Property tax assessments: how to appeal and win",
            "The hidden costs of homeownership (maintenance, opportunity cost)",
        ],
    },
    {
        "week": 37,
        "theme": "Small Business Finance",
        "topics": [
            "Cash flow management: the #1 reason businesses fail",
            "Business credit: building a credit profile separate from personal",
            "SBA loans: types, requirements, and how to qualify",
            "Business insurance: what coverage you actually need",
            "Payroll taxes and employer obligations",
            "Retirement plans for business owners: Solo 401k, SEP IRA, SIMPLE",
            "Exit planning: selling your business or passing it on",
        ],
    },
    {
        "week": 38,
        "theme": "Passive Income Strategies",
        "topics": [
            "Dividend investing: building an income-producing portfolio",
            "Rental income: the real return after expenses",
            "Bond laddering: creating predictable income streams",
            "Royalties and licensing: earning while you sleep",
            "Peer-to-peer lending: returns, risks, and platforms",
            "Creating digital products: courses, templates, and tools",
            "The passive income myth: what's actually passive vs active",
        ],
    },
    {
        "week": 39,
        "theme": "Student Finance",
        "topics": [
            "FAFSA optimization: legal strategies to maximize financial aid",
            "Student loan types: federal vs private and which to take first",
            "Income-driven repayment plans: which one saves you the most",
            "Public Service Loan Forgiveness (PSLF): qualifying and tracking",
            "Student loan refinancing: when it makes sense",
            "Paying for grad school: ROI analysis by field",
            "The student loan interest deduction and other tax benefits",
        ],
    },
    {
        "week": 40,
        "theme": "Economic Indicators",
        "topics": [
            "GDP: what it measures and why it matters to your wallet",
            "Unemployment rate: leading vs lagging indicator",
            "Consumer Price Index (CPI) and how inflation is measured",
            "Yield curve: the recession predictor explained",
            "Housing starts and what they signal about the economy",
            "Consumer confidence index: sentiment vs reality",
            "How to read economic data without panicking",
        ],
    },
    {
        "week": 41,
        "theme": "Options & Derivatives",
        "topics": [
            "Options basics: calls, puts, and why they exist",
            "Covered calls: generating income from stocks you own",
            "Protective puts: insurance for your portfolio",
            "Options pricing: intrinsic value, time value, and the Greeks",
            "Why 90% of options expire worthless (and what that means)",
            "Selling options for income: the wheel strategy",
            "When options make sense for regular investors (rarely)",
        ],
    },
    {
        "week": 42,
        "theme": "Financial Planning by Decade",
        "topics": [
            "Your 20s: building the foundation (emergency fund, 401k, credit)",
            "Your 30s: accelerating wealth (home, family, career peak)",
            "Your 40s: catch-up contributions and mid-career optimization",
            "Your 50s: retirement planning gets real (catch-up limits, Social Security)",
            "Your 60s: the transition decade (drawdown strategies, Medicare)",
            "Your 70s+: legacy planning and required distributions",
            "Age-appropriate asset allocation: shifting from growth to income",
        ],
    },
    {
        "week": 43,
        "theme": "Tax Filing Deep Dive",
        "topics": [
            "Filing status: how it affects your brackets and deductions",
            "Schedule C: freelancer and side hustle tax reporting",
            "Schedule E: rental income and real estate tax reporting",
            "Form 8949: reporting capital gains and losses",
            "Estimated tax penalties: how to avoid them",
            "Tax extensions: when to file and what it means",
            "Common audit triggers and how to minimize risk",
        ],
    },
    {
        "week": 44,
        "theme": "Frugality & Smart Spending",
        "topics": [
            "The latte factor is BS: focus on the big wins instead",
            "Negotiating recurring bills: cable, phone, insurance",
            "Meal planning and grocery optimization: $200/month savings",
            "Transportation costs: the math behind your commute",
            "Travel hacking: credit card points for free flights and hotels",
            "The cost-per-use framework for evaluating purchases",
            "When spending more saves money: quality vs cheap",
        ],
    },
    {
        "week": 45,
        "theme": "Financial Literacy Gaps",
        "topics": [
            "Why schools don't teach personal finance (and what to do about it)",
            "Financial literacy by gender: closing the knowledge gap",
            "Immigrant finance: navigating the US financial system",
            "Financial abuse: recognizing and recovering from it",
            "Predatory lending: payday loans, rent-to-own, and title loans",
            "Financial advisors: fiduciary vs suitability standard",
            "Free financial education resources that are actually good",
        ],
    },
    {
        "week": 46,
        "theme": "Market Structure",
        "topics": [
            "How the stock market actually works (order flow, market makers)",
            "ETFs vs mutual funds: structural differences that matter",
            "Index construction: how the S&P 500 picks its stocks",
            "Market hours, after-hours trading, and why it matters",
            "IPOs: how companies go public and why retail investors lose",
            "Dark pools and high-frequency trading: should you care?",
            "Fractional shares and commission-free trading: the real cost",
        ],
    },
    {
        "week": 47,
        "theme": "Risk Management",
        "topics": [
            "Understanding risk: standard deviation, beta, and Sharpe ratio",
            "Diversification: the only free lunch in investing",
            "Sequence of returns risk: the retiree's biggest threat",
            "Concentration risk: when one stock dominates your portfolio",
            "Longevity risk: the chance you'll outlive your money",
            "Inflation risk: why 'safe' investments can be dangerous",
            "Building an all-weather portfolio: Ray Dalio's approach simplified",
        ],
    },
    {
        "week": 48,
        "theme": "Life Events & Money",
        "topics": [
            "Getting married: financial to-do list for newlyweds",
            "Having a baby: the real costs and how to prepare",
            "Buying your first home: the complete financial checklist",
            "Changing careers: financial planning for a transition",
            "Inheritance: what to do when you receive a windfall",
            "Starting a family business: financial structures and pitfalls",
            "Retirement: the first 90 days of not working",
        ],
    },
    {
        "week": 49,
        "theme": "Fintech & Modern Banking",
        "topics": [
            "Neobanks vs traditional banks: where to keep your money",
            "Buy now, pay later (BNPL): hidden costs and credit impacts",
            "Mobile payment apps: Venmo, Zelle, Cash App security risks",
            "Cryptocurrency exchanges: custodial vs non-custodial",
            "AI in personal finance: what it can and can't do",
            "Open banking: how data sharing is changing finance",
            "The future of money: CBDCs, stablecoins, and digital payments",
        ],
    },
    {
        "week": 50,
        "theme": "Investment Psychology",
        "topics": [
            "The efficient market hypothesis: can anyone beat the market?",
            "Warren Buffett's rules: simple wisdom that actually works",
            "Contrarian investing: when going against the crowd pays off",
            "The disposition effect: selling winners too early, holding losers too long",
            "Information overload: why more data makes worse decisions",
            "Building an investment policy statement (your personal rules)",
            "The power of doing nothing: why most portfolio changes hurt returns",
        ],
    },
    {
        "week": 51,
        "theme": "Year-End Planning",
        "topics": [
            "Year-end tax moves: last-chance strategies before December 31",
            "Annual financial review: the complete checklist",
            "Rebalancing your portfolio for the new year",
            "Open enrollment: choosing the right health plan",
            "Updating beneficiaries and estate documents",
            "Setting financial goals that actually stick",
            "Building your financial calendar for the year ahead",
        ],
    },
    {
        "week": 52,
        "theme": "Building Your Financial System",
        "topics": [
            "The personal finance stack: accounts, tools, and automation",
            "Creating your investment policy statement",
            "Building financial habits that compound over decades",
            "Finding your financial advisor (or deciding you don't need one)",
            "The one-page financial plan: everything on a single sheet",
            "Financial independence scorecard: tracking your progress",
            "The most important financial lesson: start now, adjust later",
        ],
    },
]


def get_topic_for_date(date_str: str) -> dict:
    """Get the curriculum topic for a given date string (YYYY-MM-DD)."""
    from datetime import datetime

    dt = datetime.strptime(date_str, "%Y-%m-%d")
    day_of_year = dt.timetuple().tm_yday
    week_index = (day_of_year // 7) % len(CURRICULUM)
    day_index = day_of_year % 7

    week = CURRICULUM[week_index]
    return {
        "week_number": week["week"],
        "theme": week["theme"],
        "topic": week["topics"][day_index],
    }
